"""user_id added to proj

Revision ID: 2c4f5efd3535
Revises: 7b71c49fe5d0
Create Date: 2021-07-01 10:45:54.237122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4f5efd3535'
down_revision = '7b71c49fe5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
